import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "../../../globals.css";
import Navbar from "@/app/components/Navbar";



export const metadata: Metadata = {
  title: "Profile-App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png", // Pour PNG
    shortcut: "/favicon.png", // Alternative
    apple: "/favicon.png", // Pour iOS
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <div className="flex flex-col no-scrollbar  ">
        <Navbar />
        <main className="flex-1 py-2">{children}</main>
      </div>
    </ClerkProvider>
  );
}
