import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "../../globals.css";



export const metadata: Metadata = {
  title: "Profile-App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png", // Pour PNG
    shortcut: "/favicon.png", // Alternative
    apple: "/favicon.png", // Pour iOS
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <div className="flex h-screen">
        <main className="flex-1 pt-2 px-4">{children}</main>
      </div>
    </ClerkProvider>
  );
}
